#:import SearchVideos data.screens.Search.SearchVideos
#:import Tools data.screens.Tools.Tools
#:import Main data.screens.Main.Main
#:import Info data.screens.Info.Info

#:import Widgets data.widgets.Widgets
#:import animateWidget data.functions.animateWidget

#:import platform kivy.utils.platform
#:import Window kivy.core.window.Window

#:set mainfont "data/files/seguiemj"
#:set Mustica "data/files/Mustica"

<SM>:
    Main:
